// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Exercisediary.Shared;

/// <summary>
/// Exercise instances and their details.
/// </summary>
public partial class Exercise
{
    /// <summary>
    /// Auto generated UUID
    /// </summary>
    public Guid ExerciseId { get; set; }

    /// <summary>
    /// FK from ExerciseType table.
    /// </summary>
    public Guid ExerciseTypeId { get; set; }

    /// <summary>
    /// Place where exercise took place.
    /// </summary>
    public Guid LocationId { get; set; }

    /// <summary>
    /// Required, neede for Duration calucation.
    /// </summary>
    public DateTime StartTime { get; set; }

    /// <summary>
    /// Required, needed for Duration calculation.
    /// </summary>
    public DateTime EndTime { get; set; }

    /// <summary>
    /// Exercise duration in minutes, data base calculates.
    /// </summary>
    public int? Duration { get; set; }

    /// <summary>
    /// Average heart beat rate.
    /// </summary>
    public int? BmpCount { get; set; }

    /// <summary>
    /// Calories burned during this exercise.
    /// </summary>
    public int? CaloriesBurned { get; set; }

    /// <summary>
    /// Exercise notes.
    /// </summary>
    public string Notes { get; set; }

    /// <summary>
    /// X and Y coordinates of Startpoint.
    /// </summary>
    public decimal? StartpointLat { get; set; }

    public decimal? StartpointLong { get; set; }

    public decimal? EndpointLat { get; set; }

    /// <summary>
    /// X and Y coordinates of Endpoint.
    /// </summary>
    public decimal? EndpointLong { get; set; }

    /// <summary>
    /// Distance travelled.
    /// </summary>
    public int? MetersTraveled { get; set; }

    public virtual ExerciseType ExerciseType { get; set; }

    public virtual Location Location { get; set; }
}