// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Exercisediary.Shared;

/// <summary>
/// Place where exercise took place like &quot;New York&quot; &quot;Central Park&quot;
/// </summary>
public partial class Location
{
    public Guid LocationId { get; set; }

    /// <summary>
    /// Name of the where exercise took place.
    /// </summary>
    public string City { get; set; }

    /// <summary>
    /// Name of the exercise place, like Central Park, or Heavy Gym.
    /// </summary>
    public string Place { get; set; }
   
    public virtual ICollection<Exercise> Exercises { get; set; } = new List<Exercise>();
}